pipeline:
  name: pipeline-gitexp
  identifier: pipelinegitexp
  projectIdentifier: grand_line
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: github_main
        repoName: harness
        build: <+input>
        sparseCheckout: []
  stages:
    - stage:
        name: Security Scans
        identifier: Security_Scans
        description: This is a Snyk security Scanner
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Snyk
                  name: Snyk
                  identifier: Snyk
                  spec:
                    mode: orchestration
                    config: code
                    target:
                      type: repository
                      workspace: /harness/services/luffy
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: low
                    privileged: true
                    auth:
                      access_token: a524b527-79df-4630-a57f-7955ef67bab7
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Unknown
                        action:
                          type: Ignore
              - step:
                  type: Run
                  name: Check Validation fail
                  identifier: Check_Validation_fail
                  spec:
                    shell: Sh
                    command: echo "this need to be executed anyway"
