pipeline:
  name: DEVOPS - HARNESS TEAMS
  identifier: DEVOPS_HARNESS_TEAMS
  projectIdentifier: grand_line
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: IacSec
        identifier: IacSec
        tags: {}
        template:
          templateRef: AquaTrivy_IAC_Configuration
          versionLabel: v2.0.0
          templateInputs:
            type: IACM
            spec:
              workspace: <+input>
    - stage:
        name: Iac Issues
        identifier: Iac_Issues
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Approval
                  identifier: Approval
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    isAutoRejectEnabled: false
                    approverInputs: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors: []
              action:
                type: Abort
    - stage:
        name: Infra
        identifier: Default_Setup
        description: ""
        type: IACM
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          workspace: <+input>
          execution:
            steps:
              - step:
                  type: IACMTerraformPlugin
                  name: Init
                  identifier: Init
                  spec:
                    command: init
                  timeout: 10m
              - step:
                  type: IACMTerraformPlugin
                  name: Validate
                  identifier: Validate
                  spec:
                    command: validate
                  timeout: 10m
              - step:
                  type: IACMTerraformPlugin
                  name: Plan
                  identifier: Plan
                  spec:
                    command: plan
                  timeout: 10m
              - step:
                  type: IACMApproval
                  name: Keep Going
                  identifier: Keep_Going
                  spec:
                    autoApprove: false
                  timeout: 1h
              - step:
                  type: IACMTerraformPlugin
                  name: Apply
                  identifier: Apply
                  spec:
                    command: apply
                  timeout: 1h
        tags: {}
        failureStrategies:
          - onFailure:
              errors: []
              action:
                type: Abort
  variables:
    - name: MONOREPO_INFRA_FOLDER_PATH
      type: String
      description: ""
      required: true
      value: <+input>
